# ---------------------- PROJECT SPECIFIC ---------------------------

site_name: DataJoint Python
repo_url: https://github.com/guzman-raphael/test-docs-dj-py
repo_name: guzman-raphael/test-docs-dj-py
nav:
  - DataJoint Python: getting_started/index.md
  - Getting Started:
      - Installation: getting_started/index.md
      - Set Up: getting_started/setup.md
  - Tutorials: tutorials.md
  - Concepts: concepts.md
  - About: about.md
  - API: api.md

# ---------------------------- STANDARD -----------------------------

docs_dir: ./src
edit_uri: ./edit/main/docs/src
theme:
  name: material
  custom_dir: src/.overrides
  logo: assets/images/project-logo-black.png
  favicon: assets/images/project-logo-color.png
  features:
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: datajoint
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search
  - redirects:
      redirect_maps:
        "index.md": "getting_started/index.md"
  - mkdocstrings:
      default_handler: python
markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - pymdownx.emoji:
      options:
        custom_icons:
          - .overrides/.icons
extra:
  generator: false # Disable watermark
  version:
    provider: mike
  social:
    - icon: datajoint/company-logo
      link: https://www.datajoint.com/
    - icon: fontawesome/brands/slack
      link: https://datajoint.slack.com
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/datajoint
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/DataJointIO
    - icon: fontawesome/brands/github
      link: https://github.com/datajoint
    - icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com/questions/tagged/datajoint
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCdeCuFOTCXlVMRzh6Wk-lGg
extra_css:
  - assets/stylesheets/extra.css